### ISSUE TITLE
Documenter le code

### ISSUE THREAD

**Issue by tdurieux** [tdurieux/server_ftp#1]
J'ai écrit une bonne partie du code, je dois maintenant le documenter ... et peut-être revoir l'architecture

**Comment by toulet** [comment]
J'ai commencé à documenter le code pour bien comprendre ce qui a été fait, si tu vois une correction à effectuer n'hésite pas.

**Comment by toulet** [comment]
Je me charge du reste de la documentation.

**Comment by toulet** [comment]
Tout le code est documenté, à partir de maintenant il faut systématiquement ajouter des commentaires si l'on ajoute ou modifie une méthode.

**Comment by tdurieux** [comment]
Merci
