### ISSUE TITLE
Gérer le transfert de fichier client vers serveur

### ISSUE THREAD

**Issue by tdurieux** [tdurieux/server_ftp#3]
Le serveur sait transférer des fichiers vers le client il fait maintenant pouvoir faire le chemin inverse.

**Comment by toulet** [comment]
Hola, il faut m'en laisser un peu ! ;-)
Je m'occupe du download et de la doc lundi 3 février.

**Comment by tdurieux** [comment]
Je dois encore nettoyer le code avant de faire la doc, j'ai fais des trucs pas très propre pour tester les différentes commandes

**Comment by toulet** [comment]
Pas de problème, bon dimanche !

Le 2 février 2014 11:01, tdurieux notifications@github.com a écrit :

> Je dois encore nettoyer le code avant de faire la doc, j'ai fais des trucs
> pas très propre pour tester les différentes commandes
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/3#issuecomment-33896590
> .

## 

_Cyrille Toulet_

**Comment by tdurieux** [comment]
C'est fais ca fonctionne
