### ISSUE TITLE
Test unitaire

### ISSUE THREAD

**Issue by tdurieux** [tdurieux/server_ftp#4]
Il faudrait commencer les tests unitaires

**Comment by tdurieux** [comment]
j'ai fais le gros des tests, il reste les tests de la classe TransfertServer, quand ca sera fait je pense que les tests seront fini.

**Comment by toulet** [comment]
Je m'en charge.

**Comment by toulet** [comment]
Lorsque je lance les tests unitaires j'ai ceci :

...
testRequestEPSV(test.lille1.car2014.durieux_toulet.ftp_server.FTPRequestHandlerTest): Error execution USER error: null
testRequestEPSVNotConnected(test.lille1.car2014.durieux_toulet.ftp_server.FTPRequestHandlerTest): Could not initialize class lille1.car2014.durieux_toulet.config.FTPConfiguration
févr. 11, 2014 6:20:52 PM lille1.car2014.durieux_toulet.ftp_server.FTPServerImpl startServer
INFO: [ LOG ] FTP server started on port: 2121
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: Could not initialize class lille1.car2014.durieux_toulet.config.FTPConfiguration
    at lille1.car2014.durieux_toulet.ftp_server.FTPServerImpl.startServer(FTPServerImpl.java:68)
    at test.lille1.car2014.durieux_toulet.ftp_server.FTPServerTest$2.run(FTPServerTest.java:63)
    at java.lang.Thread.run(Thread.java:724)
Exception in thread "Thread-2" java.lang.AssertionError: Unable to start server: Port 2121 already used or reserved by the system.
    at org.junit.Assert.fail(Assert.java:93)
    at test.lille1.car2014.durieux_toulet.ftp_server.FTPServerTest$1.run(FTPServerTest.java:37)
    at java.lang.Thread.run(Thread.java:724)
testStartFTPServerWithServerAlreadyStarted(test.lille1.car2014.durieux_toulet.ftp_server.FTPServerTest): null
testStartFTPServer(test.lille1.car2014.durieux_toulet.ftp_server.FTPServerTest): expected:<false> but was:<true>
...

Les exception, c'est normal ?

**Comment by tdurieux** [comment]
J'ai pas du tout ces exceptions...

=> Port 2121 already used or reserved by the system. tu dois avoir une instances du serveur qui doit encore tourner

**Comment by toulet** [comment]
Alors au moins un des serveurs lancés pendant les tests n'est pas fermé
correctement.
Je cherche ça.

2014-02-11 18:36 GMT+01:00 Thomas Durieux notifications@github.com:

> => Port 2121 already used or reserved by the system. tu dois avoir une
> instances du serveur qui doit encore tourner
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/4#issuecomment-34780902
> .

## 

_Cyrille Toulet_

**Comment by tdurieux** [comment]
Un exception que je n'ai pas doit se lancer car je n'ai pas le problème. Ca plant sur quel test

**Comment by toulet** [comment]
testRequestEPSVNotConnected

Il reçoit 2 exceptions (une pour le thread 0 et une pour le thread 2).

2014-02-11 18:52 GMT+01:00 Thomas Durieux notifications@github.com:

> Un exception que je n'ai pas doit se lancer car je n'ai pas le problème.
> Ca plant sur quel test
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/4#issuecomment-34783852
> .

## 

_Cyrille Toulet_

**Comment by tdurieux** [comment]
Les exceptions que tu m'as donné plus haut?. Ce test et les tests précédents n'ouvre pas de connexion sur le port 2121 :S

**Comment by toulet** [comment]
En effet, j'ai commenté le code de RequestEPSVNotConnected et l'exception
est toujours là, elle doit être lancée plus haut.
Je vais trouver ça !

Le 11 février 2014 19:01, Thomas Durieux notifications@github.com a écrit
:

> Les exceptions que tu m'as donné plus haut?. Ce test et les tests
> précédents n'ouvre pas de connexion sur le port 2121 :S
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/4#issuecomment-34784825
> .

## 

_Cyrille Toulet_

**Comment by toulet** [comment]
La première vient de TestFTPServer.testStartFTPServer().

Le 11 février 2014 19:04, Cyrille Toulet cyrille.toulet@gmail.com a écrit
:

> En effet, j'ai commenté le code de RequestEPSVNotConnected et l'exception
> est toujours là, elle doit être lancée plus haut.
> Je vais trouver ça !
> 
> Le 11 février 2014 19:01, Thomas Durieux notifications@github.com a
> écrit :
> 
> Les exceptions que tu m'as donné plus haut?. Ce test et les tests
> 
> > précédents n'ouvre pas de connexion sur le port 2121 :S
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/4#issuecomment-34784825
> > .
> 
> ## 
> 
> _Cyrille Toulet_

## 

_Cyrille Toulet_

**Comment by toulet** [comment]
Et la seconde de testStartFTPServerWithServerAlreadyStarted() !

Le 11 février 2014 19:09, Cyrille Toulet cyrille.toulet@gmail.com a écrit
:

> La première vient de TestFTPServer.testStartFTPServer().
> 
> Le 11 février 2014 19:04, Cyrille Toulet cyrille.toulet@gmail.com a
> écrit :
> 
> En effet, j'ai commenté le code de RequestEPSVNotConnected et l'exception
> 
> > est toujours là, elle doit être lancée plus haut.
> > Je vais trouver ça !
> > 
> > Le 11 février 2014 19:01, Thomas Durieux notifications@github.com a
> > écrit :
> > 
> > Les exceptions que tu m'as donné plus haut?. Ce test et les tests
> > 
> > > précédents n'ouvre pas de connexion sur le port 2121 :S
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/4#issuecomment-34784825
> > > .
> > 
> > ## 
> > 
> > _Cyrille Toulet_
> 
> ## 
> 
> _Cyrille Toulet_

## 

_Cyrille Toulet_

**Comment by tdurieux** [comment]
C'est normal que ca s'affiche il me semble.C'est des erreurs qui sont loggers plus bas. Ce qui est pas terrible je te l'accorde.

 Si le test passe tout va bien.

**Comment by toulet** [comment]
Oui les tests passent à la suite.

Dans ce cas je termine les tests unitaires de TransfertServerTest, je
documente tout le beau mon et nous aurons terminé.

Le 11 février 2014 19:17, Thomas Durieux notifications@github.com a écrit
:

> C'est normal que ca s'affiche il me semble.C'est des erreurs qui sont
> loggers plus bas. Ce qui est pas terrible je te l'accorde.
> 
> Si le test passe tout va bien.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/4#issuecomment-34786413
> .

## 

_Cyrille Toulet_

**Comment by tdurieux** [comment]
Je dois encore terminer le diagramme de classes. Tu as vu le diagramme de séquence? C'est juste immonde ^^.

**Comment by toulet** [comment]
Je ne m'en sors pas dans les derniers tests de la classe TransfertServer ...
Je bloque (vers la ligne 100, readStringContent). J'ai push ce que j'avais fais, peux-tu y jeter un œil stp ? Comment ferais-tu ce test ?

**Comment by tdurieux** [comment]
push je vais regarder.

**Comment by toulet** [comment]
C'est déjà push.

**Comment by tdurieux** [comment]
J'ai fais les tests qui restait peux-tu vérifier qu'ils passent chez toi?
Merci

**Comment by toulet** [comment]
Les tests bloquent ici : 

Exception in thread "testWriteContentFileInputStream" java.lang.AssertionError: Unable to write content
    at org.junit.Assert.fail(Assert.java:93)
    at test.lille1.car2014.durieux_toulet.ftp_server.TransfertServerTest$3.run(TransfertServerTest.java:219)

Une connexion (bloquante) ne se fait pas.

**Comment by tdurieux** [comment]
Désolé je trouve pas d'ou ca vient.
