### ISSUE TITLE
A Faire ReadMe

### ISSUE THREAD

**Issue by tdurieux** [tdurieux/server_ftp#6]

**Comment by toulet** [comment]
Done.

**Comment by tdurieux** [comment]
Le readme c'est pas encore terminé:
il faut tout ca: http://www.fil.univ-lille1.fr/~monperrus/?page=consigne-tp

Le code sample n'est pas vraiment fais et il en faudrait plusieurs. J'ai pas trop d'idées

**Comment by toulet** [comment]
J'étais complètement passé au dessus de ça ! ^^

Dans les morceaux de code : le mode anonyme, le request handler. Je vois
pas trop quoi mettre d'autre.

2014-02-11 19:26 GMT+01:00 Thomas Durieux notifications@github.com:

> Reopened #6 https://github.com/tdurieux/server_ftp/issues/6.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/6
> .

## 

_Cyrille Toulet_
