### ISSUE TITLE
Compatibilité 1.6

### ISSUE THREAD

**Issue by tdurieux** [tdurieux/server_ftp#9]
***\* le project doit entre compatible 1.6: " Compatibilité binaire/API: 1.6" j'utilise une API JAVA 7 pour lister les droits des fichiers.

**Comment by toulet** [comment]
Outch ...

Le 11 février 2014 19:35, Thomas Durieux notifications@github.com a écrit
:

> ***\* le project doit entre compatible 1.6: " Compatibilité binaire/API:
> 1.6" j'utilise une API JAVA 7 pour lister les droits des fichiers.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/9
> .

## 

_Cyrille Toulet_

**Comment by tdurieux** [comment]
java 7 à plus de 2 ans, c'est abusé.Java 6 a été abandonné depuis novembre 2013. Je sens que je vais faire mon emmerdeur sur le forum...

**Comment by toulet** [comment]
Je te soutiens ! ;-)

2014-02-11 19:39 GMT+01:00 Thomas Durieux notifications@github.com:

> java 7 à plus de 2 ans c'est abusé et a été abandonné depuis novembre
> 2013. Je sens que je vais faire mon emmerdeur sur le forum...
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/9#issuecomment-34789277
> .

## 

_Cyrille Toulet_

**Comment by tdurieux** [comment]
J'ai finalement supprimé le code non compatible. pas trop de temps a perdre pour le moment
